name: anime_games_tracker
description: ...
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  cupertino_icons: ^1.0.6
  glassmorphism: ^3.0.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  flutter_colorpicker: ^1.0.3
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  
  # Charts & Visualization
  fl_chart: ^0.66.0
  
  # Date & Time
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.1
  http: ^1.1.0
  url_launcher: ^6.2.1        # NEW: To open Spotify login
  flutter_secure_storage: ^9.0.0  # NEW: Secure token storage
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true


flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"  
